/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyDetectControlnetDetectPost
 */
export interface BodyDetectControlnetDetectPost {
    /**
     * 
     * @type {string}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetModule?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetInputImages?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetProcessorRes?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetThresholdA?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetThresholdB?: number;
}

/**
 * Check if a given object implements the BodyDetectControlnetDetectPost interface.
 */
export function instanceOfBodyDetectControlnetDetectPost(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BodyDetectControlnetDetectPostFromJSON(json: any): BodyDetectControlnetDetectPost {
    return BodyDetectControlnetDetectPostFromJSONTyped(json, false);
}

export function BodyDetectControlnetDetectPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyDetectControlnetDetectPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'controlnetModule': !exists(json, 'controlnet_module') ? undefined : json['controlnet_module'],
        'controlnetInputImages': !exists(json, 'controlnet_input_images') ? undefined : json['controlnet_input_images'],
        'controlnetProcessorRes': !exists(json, 'controlnet_processor_res') ? undefined : json['controlnet_processor_res'],
        'controlnetThresholdA': !exists(json, 'controlnet_threshold_a') ? undefined : json['controlnet_threshold_a'],
        'controlnetThresholdB': !exists(json, 'controlnet_threshold_b') ? undefined : json['controlnet_threshold_b'],
    };
}

export function BodyDetectControlnetDetectPostToJSON(value?: BodyDetectControlnetDetectPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'controlnet_module': value.controlnetModule,
        'controlnet_input_images': value.controlnetInputImages,
        'controlnet_processor_res': value.controlnetProcessorRes,
        'controlnet_threshold_a': value.controlnetThresholdA,
        'controlnet_threshold_b': value.controlnetThresholdB,
    };
}

