/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ControlNetUnitRequest } from './ControlNetUnitRequest';
import {
    ControlNetUnitRequestFromJSON,
    ControlNetUnitRequestFromJSONTyped,
    ControlNetUnitRequestToJSON,
} from './ControlNetUnitRequest';

/**
 * 
 * @export
 * @interface ControlNetStableDiffusionProcessingImg2Img
 */
export interface ControlNetStableDiffusionProcessingImg2Img {
    /**
     * 
     * @type {Array<any>}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    initImages?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    resizeMode?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    denoisingStrength?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    imageCfgScale?: number;
    /**
     * 
     * @type {string}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    mask?: string;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    maskBlur?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    inpaintingFill?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    inpaintFullRes?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    inpaintFullResPadding?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    inpaintingMaskInvert?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    initialNoiseMultiplier?: number;
    /**
     * 
     * @type {string}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    prompt?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    styles?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    seed?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    subseed?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    subseedStrength?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    seedResizeFromH?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    seedResizeFromW?: number;
    /**
     * 
     * @type {string}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    samplerName?: string;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    batchSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    nIter?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    steps?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    cfgScale?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    height?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    restoreFaces?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    tiling?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    doNotSaveSamples?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    doNotSaveGrid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    negativePrompt?: string;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    eta?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    sChurn?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    sTmax?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    sTmin?: number;
    /**
     * 
     * @type {number}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    sNoise?: number;
    /**
     * 
     * @type {object}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    overrideSettings?: object;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    overrideSettingsRestoreAfterwards?: boolean;
    /**
     * 
     * @type {Array<any>}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    scriptArgs?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    samplerIndex?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    includeInitImages?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    scriptName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    sendImages?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    saveImages?: boolean;
    /**
     * 
     * @type {object}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    alwaysonScripts?: object;
    /**
     * ControlNet Processing Units
     * @type {Array<ControlNetUnitRequest>}
     * @memberof ControlNetStableDiffusionProcessingImg2Img
     */
    controlnetUnits?: Array<ControlNetUnitRequest>;
}

/**
 * Check if a given object implements the ControlNetStableDiffusionProcessingImg2Img interface.
 */
export function instanceOfControlNetStableDiffusionProcessingImg2Img(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ControlNetStableDiffusionProcessingImg2ImgFromJSON(json: any): ControlNetStableDiffusionProcessingImg2Img {
    return ControlNetStableDiffusionProcessingImg2ImgFromJSONTyped(json, false);
}

export function ControlNetStableDiffusionProcessingImg2ImgFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControlNetStableDiffusionProcessingImg2Img {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'initImages': !exists(json, 'init_images') ? undefined : json['init_images'],
        'resizeMode': !exists(json, 'resize_mode') ? undefined : json['resize_mode'],
        'denoisingStrength': !exists(json, 'denoising_strength') ? undefined : json['denoising_strength'],
        'imageCfgScale': !exists(json, 'image_cfg_scale') ? undefined : json['image_cfg_scale'],
        'mask': !exists(json, 'mask') ? undefined : json['mask'],
        'maskBlur': !exists(json, 'mask_blur') ? undefined : json['mask_blur'],
        'inpaintingFill': !exists(json, 'inpainting_fill') ? undefined : json['inpainting_fill'],
        'inpaintFullRes': !exists(json, 'inpaint_full_res') ? undefined : json['inpaint_full_res'],
        'inpaintFullResPadding': !exists(json, 'inpaint_full_res_padding') ? undefined : json['inpaint_full_res_padding'],
        'inpaintingMaskInvert': !exists(json, 'inpainting_mask_invert') ? undefined : json['inpainting_mask_invert'],
        'initialNoiseMultiplier': !exists(json, 'initial_noise_multiplier') ? undefined : json['initial_noise_multiplier'],
        'prompt': !exists(json, 'prompt') ? undefined : json['prompt'],
        'styles': !exists(json, 'styles') ? undefined : json['styles'],
        'seed': !exists(json, 'seed') ? undefined : json['seed'],
        'subseed': !exists(json, 'subseed') ? undefined : json['subseed'],
        'subseedStrength': !exists(json, 'subseed_strength') ? undefined : json['subseed_strength'],
        'seedResizeFromH': !exists(json, 'seed_resize_from_h') ? undefined : json['seed_resize_from_h'],
        'seedResizeFromW': !exists(json, 'seed_resize_from_w') ? undefined : json['seed_resize_from_w'],
        'samplerName': !exists(json, 'sampler_name') ? undefined : json['sampler_name'],
        'batchSize': !exists(json, 'batch_size') ? undefined : json['batch_size'],
        'nIter': !exists(json, 'n_iter') ? undefined : json['n_iter'],
        'steps': !exists(json, 'steps') ? undefined : json['steps'],
        'cfgScale': !exists(json, 'cfg_scale') ? undefined : json['cfg_scale'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'restoreFaces': !exists(json, 'restore_faces') ? undefined : json['restore_faces'],
        'tiling': !exists(json, 'tiling') ? undefined : json['tiling'],
        'doNotSaveSamples': !exists(json, 'do_not_save_samples') ? undefined : json['do_not_save_samples'],
        'doNotSaveGrid': !exists(json, 'do_not_save_grid') ? undefined : json['do_not_save_grid'],
        'negativePrompt': !exists(json, 'negative_prompt') ? undefined : json['negative_prompt'],
        'eta': !exists(json, 'eta') ? undefined : json['eta'],
        'sChurn': !exists(json, 's_churn') ? undefined : json['s_churn'],
        'sTmax': !exists(json, 's_tmax') ? undefined : json['s_tmax'],
        'sTmin': !exists(json, 's_tmin') ? undefined : json['s_tmin'],
        'sNoise': !exists(json, 's_noise') ? undefined : json['s_noise'],
        'overrideSettings': !exists(json, 'override_settings') ? undefined : json['override_settings'],
        'overrideSettingsRestoreAfterwards': !exists(json, 'override_settings_restore_afterwards') ? undefined : json['override_settings_restore_afterwards'],
        'scriptArgs': !exists(json, 'script_args') ? undefined : json['script_args'],
        'samplerIndex': !exists(json, 'sampler_index') ? undefined : json['sampler_index'],
        'includeInitImages': !exists(json, 'include_init_images') ? undefined : json['include_init_images'],
        'scriptName': !exists(json, 'script_name') ? undefined : json['script_name'],
        'sendImages': !exists(json, 'send_images') ? undefined : json['send_images'],
        'saveImages': !exists(json, 'save_images') ? undefined : json['save_images'],
        'alwaysonScripts': !exists(json, 'alwayson_scripts') ? undefined : json['alwayson_scripts'],
        'controlnetUnits': !exists(json, 'controlnet_units') ? undefined : ((json['controlnet_units'] as Array<any>).map(ControlNetUnitRequestFromJSON)),
    };
}

export function ControlNetStableDiffusionProcessingImg2ImgToJSON(value?: ControlNetStableDiffusionProcessingImg2Img | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'init_images': value.initImages,
        'resize_mode': value.resizeMode,
        'denoising_strength': value.denoisingStrength,
        'image_cfg_scale': value.imageCfgScale,
        'mask': value.mask,
        'mask_blur': value.maskBlur,
        'inpainting_fill': value.inpaintingFill,
        'inpaint_full_res': value.inpaintFullRes,
        'inpaint_full_res_padding': value.inpaintFullResPadding,
        'inpainting_mask_invert': value.inpaintingMaskInvert,
        'initial_noise_multiplier': value.initialNoiseMultiplier,
        'prompt': value.prompt,
        'styles': value.styles,
        'seed': value.seed,
        'subseed': value.subseed,
        'subseed_strength': value.subseedStrength,
        'seed_resize_from_h': value.seedResizeFromH,
        'seed_resize_from_w': value.seedResizeFromW,
        'sampler_name': value.samplerName,
        'batch_size': value.batchSize,
        'n_iter': value.nIter,
        'steps': value.steps,
        'cfg_scale': value.cfgScale,
        'width': value.width,
        'height': value.height,
        'restore_faces': value.restoreFaces,
        'tiling': value.tiling,
        'do_not_save_samples': value.doNotSaveSamples,
        'do_not_save_grid': value.doNotSaveGrid,
        'negative_prompt': value.negativePrompt,
        'eta': value.eta,
        's_churn': value.sChurn,
        's_tmax': value.sTmax,
        's_tmin': value.sTmin,
        's_noise': value.sNoise,
        'override_settings': value.overrideSettings,
        'override_settings_restore_afterwards': value.overrideSettingsRestoreAfterwards,
        'script_args': value.scriptArgs,
        'sampler_index': value.samplerIndex,
        'include_init_images': value.includeInitImages,
        'script_name': value.scriptName,
        'send_images': value.sendImages,
        'save_images': value.saveImages,
        'alwayson_scripts': value.alwaysonScripts,
        'controlnet_units': value.controlnetUnits === undefined ? undefined : ((value.controlnetUnits as Array<any>).map(ControlNetUnitRequestToJSON)),
    };
}

