/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControlnetResizeMode
 */
export interface ControlnetResizeMode {
}

/**
 * Check if a given object implements the ControlnetResizeMode interface.
 */
export function instanceOfControlnetResizeMode(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ControlnetResizeModeFromJSON(json: any): ControlnetResizeMode {
    return ControlnetResizeModeFromJSONTyped(json, false);
}

export function ControlnetResizeModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControlnetResizeMode {
    return json;
}

export function ControlnetResizeModeToJSON(value?: ControlnetResizeMode | null): any {
    return value;
}

