/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbeddingItem
 */
export interface EmbeddingItem {
    /**
     * The number of steps that were used to train this embedding, if available
     * @type {number}
     * @memberof EmbeddingItem
     */
    step?: number;
    /**
     * The hash of the checkpoint this embedding was trained on, if available
     * @type {string}
     * @memberof EmbeddingItem
     */
    sdCheckpoint?: string;
    /**
     * The name of the checkpoint this embedding was trained on, if available. Note that this is the name that was used by the trainer; for a stable identifier, use `sd_checkpoint` instead
     * @type {string}
     * @memberof EmbeddingItem
     */
    sdCheckpointName?: string;
    /**
     * The length of each individual vector in the embedding
     * @type {number}
     * @memberof EmbeddingItem
     */
    shape: number;
    /**
     * The number of vectors in the embedding
     * @type {number}
     * @memberof EmbeddingItem
     */
    vectors: number;
}

/**
 * Check if a given object implements the EmbeddingItem interface.
 */
export function instanceOfEmbeddingItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "shape" in value;
    isInstance = isInstance && "vectors" in value;

    return isInstance;
}

export function EmbeddingItemFromJSON(json: any): EmbeddingItem {
    return EmbeddingItemFromJSONTyped(json, false);
}

export function EmbeddingItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'step': !exists(json, 'step') ? undefined : json['step'],
        'sdCheckpoint': !exists(json, 'sd_checkpoint') ? undefined : json['sd_checkpoint'],
        'sdCheckpointName': !exists(json, 'sd_checkpoint_name') ? undefined : json['sd_checkpoint_name'],
        'shape': json['shape'],
        'vectors': json['vectors'],
    };
}

export function EmbeddingItemToJSON(value?: EmbeddingItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'step': value.step,
        'sd_checkpoint': value.sdCheckpoint,
        'sd_checkpoint_name': value.sdCheckpointName,
        'shape': value.shape,
        'vectors': value.vectors,
    };
}

