/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LatentUpscalerModeItem
 */
export interface LatentUpscalerModeItem {
    /**
     * 
     * @type {string}
     * @memberof LatentUpscalerModeItem
     */
    name: string;
}

/**
 * Check if a given object implements the LatentUpscalerModeItem interface.
 */
export function instanceOfLatentUpscalerModeItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function LatentUpscalerModeItemFromJSON(json: any): LatentUpscalerModeItem {
    return LatentUpscalerModeItemFromJSONTyped(json, false);
}

export function LatentUpscalerModeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LatentUpscalerModeItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function LatentUpscalerModeItemToJSON(value?: LatentUpscalerModeItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

