/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Options
 */
export interface Options {
    /**
     * Always save all generated images
     * @type {boolean}
     * @memberof Options
     */
    samplesSave?: boolean;
    /**
     * File format for images
     * @type {string}
     * @memberof Options
     */
    samplesFormat?: string;
    /**
     * Images filename pattern
     * @type {any}
     * @memberof Options
     */
    samplesFilenamePattern?: any | null;
    /**
     * Add number to filename when saving
     * @type {boolean}
     * @memberof Options
     */
    saveImagesAddNumber?: boolean;
    /**
     * Always save all generated image grids
     * @type {boolean}
     * @memberof Options
     */
    gridSave?: boolean;
    /**
     * File format for grids
     * @type {string}
     * @memberof Options
     */
    gridFormat?: string;
    /**
     * Add extended info (seed, prompt) to filename when saving grid
     * @type {any}
     * @memberof Options
     */
    gridExtendedFilename?: any | null;
    /**
     * Do not save grids consisting of one picture
     * @type {boolean}
     * @memberof Options
     */
    gridOnlyIfMultiple?: boolean;
    /**
     * Prevent empty spots in grid (when set to autodetect)
     * @type {any}
     * @memberof Options
     */
    gridPreventEmptySpots?: any | null;
    /**
     * Archive filename pattern
     * @type {any}
     * @memberof Options
     */
    gridZipFilenamePattern?: any | null;
    /**
     * Grid row count; use -1 for autodetect and 0 for it to be same as batch size
     * @type {number}
     * @memberof Options
     */
    nRows?: number;
    /**
     * Font for image grids that have text
     * @type {any}
     * @memberof Options
     */
    font?: any | null;
    /**
     * Text color for image grids
     * @type {string}
     * @memberof Options
     */
    gridTextActiveColor?: string;
    /**
     * Inactive text color for image grids
     * @type {string}
     * @memberof Options
     */
    gridTextInactiveColor?: string;
    /**
     * Background color for image grids
     * @type {string}
     * @memberof Options
     */
    gridBackgroundColor?: string;
    /**
     * Save text information about generation parameters as chunks to png files
     * @type {boolean}
     * @memberof Options
     */
    enablePnginfo?: boolean;
    /**
     * Create a text file next to every image with generation parameters.
     * @type {any}
     * @memberof Options
     */
    saveTxt?: any | null;
    /**
     * Save a copy of image before doing face restoration.
     * @type {any}
     * @memberof Options
     */
    saveImagesBeforeFaceRestoration?: any | null;
    /**
     * Save a copy of image before applying highres fix.
     * @type {any}
     * @memberof Options
     */
    saveImagesBeforeHighresFix?: any | null;
    /**
     * Save a copy of image before applying color correction to img2img results
     * @type {any}
     * @memberof Options
     */
    saveImagesBeforeColorCorrection?: any | null;
    /**
     * For inpainting, save a copy of the greyscale mask
     * @type {any}
     * @memberof Options
     */
    saveMask?: any | null;
    /**
     * For inpainting, save a masked composite
     * @type {any}
     * @memberof Options
     */
    saveMaskComposite?: any | null;
    /**
     * Quality for saved jpeg images
     * @type {number}
     * @memberof Options
     */
    jpegQuality?: number;
    /**
     * Use lossless compression for webp images
     * @type {any}
     * @memberof Options
     */
    webpLossless?: any | null;
    /**
     * Save copy of large images as JPG
     * @type {boolean}
     * @memberof Options
     */
    exportFor4chan?: boolean;
    /**
     * File size limit for the above option, MB
     * @type {number}
     * @memberof Options
     */
    imgDownscaleThreshold?: number;
    /**
     * Width/height limit for the above option, in pixels
     * @type {number}
     * @memberof Options
     */
    targetSideLength?: number;
    /**
     * Maximum image size
     * @type {number}
     * @memberof Options
     */
    imgMaxSizeMp?: number;
    /**
     * Use original name for output filename during batch process in extras tab
     * @type {boolean}
     * @memberof Options
     */
    useOriginalNameBatch?: boolean;
    /**
     * Use upscaler name as filename suffix in the extras tab
     * @type {any}
     * @memberof Options
     */
    useUpscalerNameAsSuffix?: any | null;
    /**
     * When using 'Save' button, only save a single selected image
     * @type {boolean}
     * @memberof Options
     */
    saveSelectedOnly?: boolean;
    /**
     * Save init images when using img2img
     * @type {any}
     * @memberof Options
     */
    saveInitImg?: any | null;
    /**
     * Directory for temporary images; leave empty for default
     * @type {any}
     * @memberof Options
     */
    tempDir?: any | null;
    /**
     * Cleanup non-default temporary directory when starting webui
     * @type {any}
     * @memberof Options
     */
    cleanTempDirAtStart?: any | null;
    /**
     * Save incomplete images
     * @type {any}
     * @memberof Options
     */
    saveIncompleteImages?: any | null;
    /**
     * Output directory for images; if empty, defaults to three directories below
     * @type {any}
     * @memberof Options
     */
    outdirSamples?: any | null;
    /**
     * Output directory for txt2img images
     * @type {string}
     * @memberof Options
     */
    outdirTxt2imgSamples?: string;
    /**
     * Output directory for img2img images
     * @type {string}
     * @memberof Options
     */
    outdirImg2imgSamples?: string;
    /**
     * Output directory for images from extras tab
     * @type {string}
     * @memberof Options
     */
    outdirExtrasSamples?: string;
    /**
     * Output directory for grids; if empty, defaults to two directories below
     * @type {any}
     * @memberof Options
     */
    outdirGrids?: any | null;
    /**
     * Output directory for txt2img grids
     * @type {string}
     * @memberof Options
     */
    outdirTxt2imgGrids?: string;
    /**
     * Output directory for img2img grids
     * @type {string}
     * @memberof Options
     */
    outdirImg2imgGrids?: string;
    /**
     * Directory for saving images using the Save button
     * @type {string}
     * @memberof Options
     */
    outdirSave?: string;
    /**
     * Directory for saving init images when using img2img
     * @type {string}
     * @memberof Options
     */
    outdirInitImages?: string;
    /**
     * Save images to a subdirectory
     * @type {boolean}
     * @memberof Options
     */
    saveToDirs?: boolean;
    /**
     * Save grids to a subdirectory
     * @type {boolean}
     * @memberof Options
     */
    gridSaveToDirs?: boolean;
    /**
     * When using "Save" button, save images to a subdirectory
     * @type {any}
     * @memberof Options
     */
    useSaveToDirsForUi?: any | null;
    /**
     * Directory name pattern
     * @type {string}
     * @memberof Options
     */
    directoriesFilenamePattern?: string;
    /**
     * Max prompt words for [prompt_words] pattern
     * @type {number}
     * @memberof Options
     */
    directoriesMaxPromptWords?: number;
    /**
     * Tile size for ESRGAN upscalers.
     * @type {number}
     * @memberof Options
     */
    eSRGANTile?: number;
    /**
     * Tile overlap for ESRGAN upscalers.
     * @type {number}
     * @memberof Options
     */
    eSRGANTileOverlap?: number;
    /**
     * Select which Real-ESRGAN models to show in the web UI.
     * @type {Array<any>}
     * @memberof Options
     */
    realesrganEnabledModels?: Array<any>;
    /**
     * Upscaler for img2img
     * @type {any}
     * @memberof Options
     */
    upscalerForImg2img?: any | null;
    /**
     * Restore faces
     * @type {any}
     * @memberof Options
     */
    faceRestoration?: any | null;
    /**
     * Face restoration model
     * @type {string}
     * @memberof Options
     */
    faceRestorationModel?: string;
    /**
     * CodeFormer weight
     * @type {number}
     * @memberof Options
     */
    codeFormerWeight?: number;
    /**
     * Move face restoration model from VRAM into RAM after processing
     * @type {any}
     * @memberof Options
     */
    faceRestorationUnload?: any | null;
    /**
     * Automatically open webui in browser on startup
     * @type {string}
     * @memberof Options
     */
    autoLaunchBrowser?: string;
    /**
     * Show warnings in console.
     * @type {any}
     * @memberof Options
     */
    showWarnings?: any | null;
    /**
     * Show gradio deprecation warnings in console.
     * @type {boolean}
     * @memberof Options
     */
    showGradioDeprecationWarnings?: boolean;
    /**
     * VRAM usage polls per second during generation.
     * @type {number}
     * @memberof Options
     */
    memmonPollRate?: number;
    /**
     * Always print all generation info to standard output
     * @type {any}
     * @memberof Options
     */
    samplesLogStdout?: any | null;
    /**
     * Add a second progress bar to the console that shows progress for an entire job.
     * @type {boolean}
     * @memberof Options
     */
    multipleTqdm?: boolean;
    /**
     * Print extra hypernetwork information to console.
     * @type {any}
     * @memberof Options
     */
    printHypernetExtra?: any | null;
    /**
     * Load models/files in hidden directories
     * @type {boolean}
     * @memberof Options
     */
    listHiddenFiles?: boolean;
    /**
     * Disable memmapping for loading .safetensors files.
     * @type {any}
     * @memberof Options
     */
    disableMmapLoadSafetensors?: any | null;
    /**
     * Prevent Stability-AI's ldm/sgm modules from printing noise to console.
     * @type {boolean}
     * @memberof Options
     */
    hideLdmPrints?: boolean;
    /**
     * Allow http:// and https:// URLs for input images in API
     * @type {boolean}
     * @memberof Options
     */
    apiEnableRequests?: boolean;
    /**
     * Forbid URLs to local resources
     * @type {boolean}
     * @memberof Options
     */
    apiForbidLocalRequests?: boolean;
    /**
     * User agent for requests
     * @type {any}
     * @memberof Options
     */
    apiUseragent?: any | null;
    /**
     * Move VAE and CLIP to RAM when training if possible. Saves VRAM.
     * @type {any}
     * @memberof Options
     */
    unloadModelsWhenTraining?: any | null;
    /**
     * Turn on pin_memory for DataLoader. Makes training slightly faster but can increase memory usage.
     * @type {any}
     * @memberof Options
     */
    pinMemory?: any | null;
    /**
     * Saves Optimizer state as separate *.optim file. Training of embedding or HN can be resumed with the matching optim file.
     * @type {any}
     * @memberof Options
     */
    saveOptimizerState?: any | null;
    /**
     * Save textual inversion and hypernet settings to a text file whenever training starts.
     * @type {boolean}
     * @memberof Options
     */
    saveTrainingSettingsToTxt?: boolean;
    /**
     * Filename word regex
     * @type {any}
     * @memberof Options
     */
    datasetFilenameWordRegex?: any | null;
    /**
     * Filename join string
     * @type {string}
     * @memberof Options
     */
    datasetFilenameJoinString?: string;
    /**
     * Number of repeats for a single input image per epoch; used only for displaying epoch number
     * @type {number}
     * @memberof Options
     */
    trainingImageRepeatsPerEpoch?: number;
    /**
     * Save an csv containing the loss to log directory every N steps, 0 to disable
     * @type {number}
     * @memberof Options
     */
    trainingWriteCsvEvery?: number;
    /**
     * Use cross attention optimizations while training
     * @type {any}
     * @memberof Options
     */
    trainingXattentionOptimizations?: any | null;
    /**
     * Enable tensorboard logging.
     * @type {any}
     * @memberof Options
     */
    trainingEnableTensorboard?: any | null;
    /**
     * Save generated images within tensorboard.
     * @type {any}
     * @memberof Options
     */
    trainingTensorboardSaveImages?: any | null;
    /**
     * How often, in seconds, to flush the pending tensorboard events and summaries to disk.
     * @type {number}
     * @memberof Options
     */
    trainingTensorboardFlushEvery?: number;
    /**
     * Stable Diffusion checkpoint
     * @type {any}
     * @memberof Options
     */
    sdModelCheckpoint?: any | null;
    /**
     * Maximum number of checkpoints loaded at the same time
     * @type {number}
     * @memberof Options
     */
    sdCheckpointsLimit?: number;
    /**
     * Only keep one model on device
     * @type {boolean}
     * @memberof Options
     */
    sdCheckpointsKeepInCpu?: boolean;
    /**
     * Checkpoints to cache in RAM
     * @type {any}
     * @memberof Options
     */
    sdCheckpointCache?: any | null;
    /**
     * SD Unet
     * @type {string}
     * @memberof Options
     */
    sdUnet?: string;
    /**
     * Enable quantization in K samplers for sharper and cleaner results. This may change existing seeds
     * @type {any}
     * @memberof Options
     */
    enableQuantization?: any | null;
    /**
     * Enable emphasis
     * @type {boolean}
     * @memberof Options
     */
    enableEmphasis?: boolean;
    /**
     * Make K-diffusion samplers produce same images in a batch as when making a single image
     * @type {boolean}
     * @memberof Options
     */
    enableBatchSeeds?: boolean;
    /**
     * Prompt word wrap length limit
     * @type {number}
     * @memberof Options
     */
    commaPaddingBacktrack?: number;
    /**
     * Clip skip
     * @type {number}
     * @memberof Options
     */
    cLIPStopAtLastLayers?: number;
    /**
     * Upcast cross attention layer to float32
     * @type {any}
     * @memberof Options
     */
    upcastAttn?: any | null;
    /**
     * Random number generator source.
     * @type {string}
     * @memberof Options
     */
    randnSource?: string;
    /**
     * Tiling
     * @type {any}
     * @memberof Options
     */
    tiling?: any | null;
    /**
     * Hires fix: which pass to enable refiner for
     * @type {string}
     * @memberof Options
     */
    hiresFixRefinerPass?: string;
    /**
     * crop top coordinate
     * @type {any}
     * @memberof Options
     */
    sdxlCropTop?: any | null;
    /**
     * crop left coordinate
     * @type {any}
     * @memberof Options
     */
    sdxlCropLeft?: any | null;
    /**
     * SDXL low aesthetic score
     * @type {number}
     * @memberof Options
     */
    sdxlRefinerLowAestheticScore?: number;
    /**
     * SDXL high aesthetic score
     * @type {number}
     * @memberof Options
     */
    sdxlRefinerHighAestheticScore?: number;
    /**
     * 
     * @type {string}
     * @memberof Options
     */
    sdVaeExplanation?: string;
    /**
     * VAE Checkpoints to cache in RAM
     * @type {any}
     * @memberof Options
     */
    sdVaeCheckpointCache?: any | null;
    /**
     * SD VAE
     * @type {string}
     * @memberof Options
     */
    sdVae?: string;
    /**
     * Selected VAE overrides per-model preferences
     * @type {boolean}
     * @memberof Options
     */
    sdVaeOverridesPerModelPreferences?: boolean;
    /**
     * Automatically revert VAE to 32-bit floats
     * @type {boolean}
     * @memberof Options
     */
    autoVaePrecision?: boolean;
    /**
     * VAE type for encode
     * @type {string}
     * @memberof Options
     */
    sdVaeEncodeMethod?: string;
    /**
     * VAE type for decode
     * @type {string}
     * @memberof Options
     */
    sdVaeDecodeMethod?: string;
    /**
     * Inpainting conditioning mask strength
     * @type {number}
     * @memberof Options
     */
    inpaintingMaskWeight?: number;
    /**
     * Noise multiplier for img2img
     * @type {number}
     * @memberof Options
     */
    initialNoiseMultiplier?: number;
    /**
     * Extra noise multiplier for img2img and hires fix
     * @type {any}
     * @memberof Options
     */
    img2imgExtraNoise?: any | null;
    /**
     * Apply color correction to img2img results to match original colors.
     * @type {any}
     * @memberof Options
     */
    img2imgColorCorrection?: any | null;
    /**
     * With img2img, do exactly the amount of steps the slider specifies.
     * @type {any}
     * @memberof Options
     */
    img2imgFixSteps?: any | null;
    /**
     * With img2img, fill transparent parts of the input image with this color.
     * @type {string}
     * @memberof Options
     */
    img2imgBackgroundColor?: string;
    /**
     * Height of the image editor
     * @type {number}
     * @memberof Options
     */
    img2imgEditorHeight?: number;
    /**
     * Sketch initial brush color
     * @type {string}
     * @memberof Options
     */
    img2imgSketchDefaultBrushColor?: string;
    /**
     * Inpaint mask brush color
     * @type {string}
     * @memberof Options
     */
    img2imgInpaintMaskBrushColor?: string;
    /**
     * Inpaint sketch initial brush color
     * @type {string}
     * @memberof Options
     */
    img2imgInpaintSketchDefaultBrushColor?: string;
    /**
     * For inpainting, include the greyscale mask in results for web
     * @type {any}
     * @memberof Options
     */
    returnMask?: any | null;
    /**
     * For inpainting, include masked composite in results for web
     * @type {any}
     * @memberof Options
     */
    returnMaskComposite?: any | null;
    /**
     * Cross attention optimization
     * @type {string}
     * @memberof Options
     */
    crossAttentionOptimization?: string;
    /**
     * Negative Guidance minimum sigma
     * @type {any}
     * @memberof Options
     */
    sMinUncond?: any | null;
    /**
     * Token merging ratio
     * @type {any}
     * @memberof Options
     */
    tokenMergingRatio?: any | null;
    /**
     * Token merging ratio for img2img
     * @type {any}
     * @memberof Options
     */
    tokenMergingRatioImg2img?: any | null;
    /**
     * Token merging ratio for high-res pass
     * @type {any}
     * @memberof Options
     */
    tokenMergingRatioHr?: any | null;
    /**
     * Pad prompt/negative prompt to be same length
     * @type {any}
     * @memberof Options
     */
    padCondUncond?: any | null;
    /**
     * Persistent cond cache
     * @type {boolean}
     * @memberof Options
     */
    persistentCondCache?: boolean;
    /**
     * Batch cond/uncond
     * @type {boolean}
     * @memberof Options
     */
    batchCondUncond?: boolean;
    /**
     * Use old emphasis implementation. Can be useful to reproduce old seeds.
     * @type {any}
     * @memberof Options
     */
    useOldEmphasisImplementation?: any | null;
    /**
     * Use old karras scheduler sigmas (0.1 to 10).
     * @type {any}
     * @memberof Options
     */
    useOldKarrasSchedulerSigmas?: any | null;
    /**
     * Do not make DPM++ SDE deterministic across different batch sizes.
     * @type {any}
     * @memberof Options
     */
    noDpmppSdeBatchDeterminism?: any | null;
    /**
     * For hires fix, use width/height sliders to set final resolution rather than first pass (disables Upscale by, Resize width/height to).
     * @type {any}
     * @memberof Options
     */
    useOldHiresFixWidthHeight?: any | null;
    /**
     * Do not fix prompt schedule for second order samplers.
     * @type {any}
     * @memberof Options
     */
    dontFixSecondOrderSamplersSchedule?: any | null;
    /**
     * For hires fix, calculate conds of second pass using extra networks of first pass.
     * @type {any}
     * @memberof Options
     */
    hiresFixUseFirstpassConds?: any | null;
    /**
     * Use old prompt editing timelines.
     * @type {any}
     * @memberof Options
     */
    useOldScheduling?: any | null;
    /**
     * Keep models in VRAM
     * @type {any}
     * @memberof Options
     */
    interrogateKeepModelsInMemory?: any | null;
    /**
     * Include ranks of model tags matches in results.
     * @type {any}
     * @memberof Options
     */
    interrogateReturnRanks?: any | null;
    /**
     * BLIP: num_beams
     * @type {number}
     * @memberof Options
     */
    interrogateClipNumBeams?: number;
    /**
     * BLIP: minimum description length
     * @type {number}
     * @memberof Options
     */
    interrogateClipMinLength?: number;
    /**
     * BLIP: maximum description length
     * @type {number}
     * @memberof Options
     */
    interrogateClipMaxLength?: number;
    /**
     * CLIP: maximum number of lines in text file
     * @type {number}
     * @memberof Options
     */
    interrogateClipDictLimit?: number;
    /**
     * CLIP: skip inquire categories
     * @type {any}
     * @memberof Options
     */
    interrogateClipSkipCategories?: any | null;
    /**
     * deepbooru: score threshold
     * @type {number}
     * @memberof Options
     */
    interrogateDeepbooruScoreThreshold?: number;
    /**
     * deepbooru: sort tags alphabetically
     * @type {boolean}
     * @memberof Options
     */
    deepbooruSortAlpha?: boolean;
    /**
     * deepbooru: use spaces in tags
     * @type {boolean}
     * @memberof Options
     */
    deepbooruUseSpaces?: boolean;
    /**
     * deepbooru: escape (\) brackets
     * @type {boolean}
     * @memberof Options
     */
    deepbooruEscape?: boolean;
    /**
     * deepbooru: filter out those tags
     * @type {any}
     * @memberof Options
     */
    deepbooruFilterTags?: any | null;
    /**
     * Show hidden directories
     * @type {boolean}
     * @memberof Options
     */
    extraNetworksShowHiddenDirectories?: boolean;
    /**
     * Show cards for models in hidden directories
     * @type {string}
     * @memberof Options
     */
    extraNetworksHiddenModels?: string;
    /**
     * Default multiplier for extra networks
     * @type {number}
     * @memberof Options
     */
    extraNetworksDefaultMultiplier?: number;
    /**
     * Card width for Extra Networks
     * @type {any}
     * @memberof Options
     */
    extraNetworksCardWidth?: any | null;
    /**
     * Card height for Extra Networks
     * @type {any}
     * @memberof Options
     */
    extraNetworksCardHeight?: any | null;
    /**
     * Card text scale
     * @type {number}
     * @memberof Options
     */
    extraNetworksCardTextScale?: number;
    /**
     * Show description on card
     * @type {boolean}
     * @memberof Options
     */
    extraNetworksCardShowDesc?: boolean;
    /**
     * Extra networks separator
     * @type {string}
     * @memberof Options
     */
    extraNetworksAddTextSeparator?: string;
    /**
     * Extra networks tab order
     * @type {any}
     * @memberof Options
     */
    uiExtraNetworksTabReorder?: any | null;
    /**
     * Print a list of Textual Inversion embeddings when loading model
     * @type {any}
     * @memberof Options
     */
    textualInversionPrintAtLoad?: any | null;
    /**
     * Add Textual Inversion hashes to infotext
     * @type {boolean}
     * @memberof Options
     */
    textualInversionAddHashesToInfotext?: boolean;
    /**
     * Add hypernetwork to prompt
     * @type {string}
     * @memberof Options
     */
    sdHypernetwork?: string;
    /**
     * Localization
     * @type {string}
     * @memberof Options
     */
    localization?: string;
    /**
     * Gradio theme
     * @type {string}
     * @memberof Options
     */
    gradioTheme?: string;
    /**
     * Cache gradio themes locally
     * @type {boolean}
     * @memberof Options
     */
    gradioThemesCache?: boolean;
    /**
     * Gallery height
     * @type {any}
     * @memberof Options
     */
    galleryHeight?: any | null;
    /**
     * Show grid in results for web
     * @type {boolean}
     * @memberof Options
     */
    returnGrid?: boolean;
    /**
     * Do not show any images in results for web
     * @type {any}
     * @memberof Options
     */
    doNotShowImages?: any | null;
    /**
     * Send seed when sending prompt or image to other interface
     * @type {boolean}
     * @memberof Options
     */
    sendSeed?: boolean;
    /**
     * Send size when sending prompt or image to another interface
     * @type {boolean}
     * @memberof Options
     */
    sendSize?: boolean;
    /**
     * Enable full page image viewer
     * @type {boolean}
     * @memberof Options
     */
    jsModalLightbox?: boolean;
    /**
     * Show images zoomed in by default in full page image viewer
     * @type {boolean}
     * @memberof Options
     */
    jsModalLightboxInitiallyZoomed?: boolean;
    /**
     * Navigate image viewer with gamepad
     * @type {any}
     * @memberof Options
     */
    jsModalLightboxGamepad?: any | null;
    /**
     * Gamepad repeat period, in milliseconds
     * @type {number}
     * @memberof Options
     */
    jsModalLightboxGamepadRepeat?: number;
    /**
     * Show generation progress in window title.
     * @type {boolean}
     * @memberof Options
     */
    showProgressInTitle?: boolean;
    /**
     * Use dropdown for sampler selection instead of radio group
     * @type {boolean}
     * @memberof Options
     */
    samplersInDropdown?: boolean;
    /**
     * Show Width/Height and Batch sliders in same row
     * @type {boolean}
     * @memberof Options
     */
    dimensionsAndBatchTogether?: boolean;
    /**
     * Ctrl+up/down precision when editing (attention:1.1)
     * @type {number}
     * @memberof Options
     */
    keyeditPrecisionAttention?: number;
    /**
     * Ctrl+up/down precision when editing <extra networks:0.9>
     * @type {number}
     * @memberof Options
     */
    keyeditPrecisionExtra?: number;
    /**
     * Ctrl+up/down word delimiters
     * @type {string}
     * @memberof Options
     */
    keyeditDelimiters?: string;
    /**
     * Alt+left/right moves prompt elements
     * @type {boolean}
     * @memberof Options
     */
    keyeditMove?: boolean;
    /**
     * Quicksettings list
     * @type {Array<any>}
     * @memberof Options
     */
    quicksettingsList?: Array<any>;
    /**
     * UI tab order
     * @type {any}
     * @memberof Options
     */
    uiTabOrder?: any | null;
    /**
     * Hidden UI tabs
     * @type {any}
     * @memberof Options
     */
    hiddenTabs?: any | null;
    /**
     * txt2img/img2img UI item order
     * @type {any}
     * @memberof Options
     */
    uiReorderList?: any | null;
    /**
     * Hires fix: show hires checkpoint and sampler selection
     * @type {any}
     * @memberof Options
     */
    hiresFixShowSampler?: any | null;
    /**
     * Hires fix: show hires prompt and negative prompt
     * @type {any}
     * @memberof Options
     */
    hiresFixShowPrompts?: any | null;
    /**
     * Disable prompt token counters
     * @type {any}
     * @memberof Options
     */
    disableTokenCounters?: any | null;
    /**
     * Add model hash to generation information
     * @type {boolean}
     * @memberof Options
     */
    addModelHashToInfo?: boolean;
    /**
     * Add model name to generation information
     * @type {boolean}
     * @memberof Options
     */
    addModelNameToInfo?: boolean;
    /**
     * Add user name to generation information when authenticated
     * @type {any}
     * @memberof Options
     */
    addUserNameToInfo?: any | null;
    /**
     * Add program version to generation information
     * @type {boolean}
     * @memberof Options
     */
    addVersionToInfotext?: boolean;
    /**
     * Disregard checkpoint information from pasted infotext
     * @type {boolean}
     * @memberof Options
     */
    disableWeightsAutoSwap?: boolean;
    /**
     * Infer styles from prompts of pasted infotext
     * @type {string}
     * @memberof Options
     */
    infotextStyles?: string;
    /**
     * Show progressbar
     * @type {boolean}
     * @memberof Options
     */
    showProgressbar?: boolean;
    /**
     * Show live previews of the created image
     * @type {boolean}
     * @memberof Options
     */
    livePreviewsEnable?: boolean;
    /**
     * Live preview file format
     * @type {string}
     * @memberof Options
     */
    livePreviewsImageFormat?: string;
    /**
     * Show previews of all images generated in a batch as a grid
     * @type {boolean}
     * @memberof Options
     */
    showProgressGrid?: boolean;
    /**
     * Live preview display period
     * @type {number}
     * @memberof Options
     */
    showProgressEveryNSteps?: number;
    /**
     * Live preview method
     * @type {string}
     * @memberof Options
     */
    showProgressType?: string;
    /**
     * Allow Full live preview method with lowvram/medvram
     * @type {any}
     * @memberof Options
     */
    livePreviewAllowLowvramFull?: any | null;
    /**
     * Live preview subject
     * @type {string}
     * @memberof Options
     */
    livePreviewContent?: string;
    /**
     * Progressbar and preview update period
     * @type {number}
     * @memberof Options
     */
    livePreviewRefreshPeriod?: number;
    /**
     * Return image with chosen live preview method on interrupt
     * @type {any}
     * @memberof Options
     */
    livePreviewFastInterrupt?: any | null;
    /**
     * Hide samplers in user interface
     * @type {any}
     * @memberof Options
     */
    hideSamplers?: any | null;
    /**
     * Eta for DDIM
     * @type {any}
     * @memberof Options
     */
    etaDdim?: any | null;
    /**
     * Eta for k-diffusion samplers
     * @type {number}
     * @memberof Options
     */
    etaAncestral?: number;
    /**
     * img2img DDIM discretize
     * @type {string}
     * @memberof Options
     */
    ddimDiscretize?: string;
    /**
     * sigma churn
     * @type {any}
     * @memberof Options
     */
    sChurn?: any | null;
    /**
     * sigma tmin
     * @type {any}
     * @memberof Options
     */
    sTmin?: any | null;
    /**
     * sigma tmax
     * @type {any}
     * @memberof Options
     */
    sTmax?: any | null;
    /**
     * sigma noise
     * @type {number}
     * @memberof Options
     */
    sNoise?: number;
    /**
     * Scheduler type
     * @type {string}
     * @memberof Options
     */
    kSchedType?: string;
    /**
     * sigma min
     * @type {any}
     * @memberof Options
     */
    sigmaMin?: any | null;
    /**
     * sigma max
     * @type {any}
     * @memberof Options
     */
    sigmaMax?: any | null;
    /**
     * rho
     * @type {any}
     * @memberof Options
     */
    rho?: any | null;
    /**
     * Eta noise seed delta
     * @type {any}
     * @memberof Options
     */
    etaNoiseSeedDelta?: any | null;
    /**
     * Always discard next-to-last sigma
     * @type {any}
     * @memberof Options
     */
    alwaysDiscardNextToLastSigma?: any | null;
    /**
     * SGM noise multiplier
     * @type {any}
     * @memberof Options
     */
    sgmNoiseMultiplier?: any | null;
    /**
     * UniPC variant
     * @type {string}
     * @memberof Options
     */
    uniPcVariant?: string;
    /**
     * UniPC skip type
     * @type {string}
     * @memberof Options
     */
    uniPcSkipType?: string;
    /**
     * UniPC order
     * @type {number}
     * @memberof Options
     */
    uniPcOrder?: number;
    /**
     * UniPC lower order final
     * @type {boolean}
     * @memberof Options
     */
    uniPcLowerOrderFinal?: boolean;
    /**
     * Enable postprocessing operations in txt2img and img2img tabs
     * @type {any}
     * @memberof Options
     */
    postprocessingEnableInMainUi?: any | null;
    /**
     * Postprocessing operation order
     * @type {any}
     * @memberof Options
     */
    postprocessingOperationOrder?: any | null;
    /**
     * Maximum number of images in upscaling cache
     * @type {number}
     * @memberof Options
     */
    upscalingMaxImagesInCache?: number;
    /**
     * Disable these extensions
     * @type {any}
     * @memberof Options
     */
    disabledExtensions?: any | null;
    /**
     * Disable all extensions (preserves the list of disabled extensions)
     * @type {string}
     * @memberof Options
     */
    disableAllExtensions?: string;
    /**
     * Config state file to restore from, under 'config-states/' folder
     * @type {any}
     * @memberof Options
     */
    restoreConfigStateFile?: any | null;
    /**
     * SHA256 hash of the current checkpoint
     * @type {any}
     * @memberof Options
     */
    sdCheckpointHash?: any | null;
}

/**
 * Check if a given object implements the Options interface.
 */
export function instanceOfOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OptionsFromJSON(json: any): Options {
    return OptionsFromJSONTyped(json, false);
}

export function OptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Options {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'samplesSave': !exists(json, 'samples_save') ? undefined : json['samples_save'],
        'samplesFormat': !exists(json, 'samples_format') ? undefined : json['samples_format'],
        'samplesFilenamePattern': !exists(json, 'samples_filename_pattern') ? undefined : json['samples_filename_pattern'],
        'saveImagesAddNumber': !exists(json, 'save_images_add_number') ? undefined : json['save_images_add_number'],
        'gridSave': !exists(json, 'grid_save') ? undefined : json['grid_save'],
        'gridFormat': !exists(json, 'grid_format') ? undefined : json['grid_format'],
        'gridExtendedFilename': !exists(json, 'grid_extended_filename') ? undefined : json['grid_extended_filename'],
        'gridOnlyIfMultiple': !exists(json, 'grid_only_if_multiple') ? undefined : json['grid_only_if_multiple'],
        'gridPreventEmptySpots': !exists(json, 'grid_prevent_empty_spots') ? undefined : json['grid_prevent_empty_spots'],
        'gridZipFilenamePattern': !exists(json, 'grid_zip_filename_pattern') ? undefined : json['grid_zip_filename_pattern'],
        'nRows': !exists(json, 'n_rows') ? undefined : json['n_rows'],
        'font': !exists(json, 'font') ? undefined : json['font'],
        'gridTextActiveColor': !exists(json, 'grid_text_active_color') ? undefined : json['grid_text_active_color'],
        'gridTextInactiveColor': !exists(json, 'grid_text_inactive_color') ? undefined : json['grid_text_inactive_color'],
        'gridBackgroundColor': !exists(json, 'grid_background_color') ? undefined : json['grid_background_color'],
        'enablePnginfo': !exists(json, 'enable_pnginfo') ? undefined : json['enable_pnginfo'],
        'saveTxt': !exists(json, 'save_txt') ? undefined : json['save_txt'],
        'saveImagesBeforeFaceRestoration': !exists(json, 'save_images_before_face_restoration') ? undefined : json['save_images_before_face_restoration'],
        'saveImagesBeforeHighresFix': !exists(json, 'save_images_before_highres_fix') ? undefined : json['save_images_before_highres_fix'],
        'saveImagesBeforeColorCorrection': !exists(json, 'save_images_before_color_correction') ? undefined : json['save_images_before_color_correction'],
        'saveMask': !exists(json, 'save_mask') ? undefined : json['save_mask'],
        'saveMaskComposite': !exists(json, 'save_mask_composite') ? undefined : json['save_mask_composite'],
        'jpegQuality': !exists(json, 'jpeg_quality') ? undefined : json['jpeg_quality'],
        'webpLossless': !exists(json, 'webp_lossless') ? undefined : json['webp_lossless'],
        'exportFor4chan': !exists(json, 'export_for_4chan') ? undefined : json['export_for_4chan'],
        'imgDownscaleThreshold': !exists(json, 'img_downscale_threshold') ? undefined : json['img_downscale_threshold'],
        'targetSideLength': !exists(json, 'target_side_length') ? undefined : json['target_side_length'],
        'imgMaxSizeMp': !exists(json, 'img_max_size_mp') ? undefined : json['img_max_size_mp'],
        'useOriginalNameBatch': !exists(json, 'use_original_name_batch') ? undefined : json['use_original_name_batch'],
        'useUpscalerNameAsSuffix': !exists(json, 'use_upscaler_name_as_suffix') ? undefined : json['use_upscaler_name_as_suffix'],
        'saveSelectedOnly': !exists(json, 'save_selected_only') ? undefined : json['save_selected_only'],
        'saveInitImg': !exists(json, 'save_init_img') ? undefined : json['save_init_img'],
        'tempDir': !exists(json, 'temp_dir') ? undefined : json['temp_dir'],
        'cleanTempDirAtStart': !exists(json, 'clean_temp_dir_at_start') ? undefined : json['clean_temp_dir_at_start'],
        'saveIncompleteImages': !exists(json, 'save_incomplete_images') ? undefined : json['save_incomplete_images'],
        'outdirSamples': !exists(json, 'outdir_samples') ? undefined : json['outdir_samples'],
        'outdirTxt2imgSamples': !exists(json, 'outdir_txt2img_samples') ? undefined : json['outdir_txt2img_samples'],
        'outdirImg2imgSamples': !exists(json, 'outdir_img2img_samples') ? undefined : json['outdir_img2img_samples'],
        'outdirExtrasSamples': !exists(json, 'outdir_extras_samples') ? undefined : json['outdir_extras_samples'],
        'outdirGrids': !exists(json, 'outdir_grids') ? undefined : json['outdir_grids'],
        'outdirTxt2imgGrids': !exists(json, 'outdir_txt2img_grids') ? undefined : json['outdir_txt2img_grids'],
        'outdirImg2imgGrids': !exists(json, 'outdir_img2img_grids') ? undefined : json['outdir_img2img_grids'],
        'outdirSave': !exists(json, 'outdir_save') ? undefined : json['outdir_save'],
        'outdirInitImages': !exists(json, 'outdir_init_images') ? undefined : json['outdir_init_images'],
        'saveToDirs': !exists(json, 'save_to_dirs') ? undefined : json['save_to_dirs'],
        'gridSaveToDirs': !exists(json, 'grid_save_to_dirs') ? undefined : json['grid_save_to_dirs'],
        'useSaveToDirsForUi': !exists(json, 'use_save_to_dirs_for_ui') ? undefined : json['use_save_to_dirs_for_ui'],
        'directoriesFilenamePattern': !exists(json, 'directories_filename_pattern') ? undefined : json['directories_filename_pattern'],
        'directoriesMaxPromptWords': !exists(json, 'directories_max_prompt_words') ? undefined : json['directories_max_prompt_words'],
        'eSRGANTile': !exists(json, 'ESRGAN_tile') ? undefined : json['ESRGAN_tile'],
        'eSRGANTileOverlap': !exists(json, 'ESRGAN_tile_overlap') ? undefined : json['ESRGAN_tile_overlap'],
        'realesrganEnabledModels': !exists(json, 'realesrgan_enabled_models') ? undefined : json['realesrgan_enabled_models'],
        'upscalerForImg2img': !exists(json, 'upscaler_for_img2img') ? undefined : json['upscaler_for_img2img'],
        'faceRestoration': !exists(json, 'face_restoration') ? undefined : json['face_restoration'],
        'faceRestorationModel': !exists(json, 'face_restoration_model') ? undefined : json['face_restoration_model'],
        'codeFormerWeight': !exists(json, 'code_former_weight') ? undefined : json['code_former_weight'],
        'faceRestorationUnload': !exists(json, 'face_restoration_unload') ? undefined : json['face_restoration_unload'],
        'autoLaunchBrowser': !exists(json, 'auto_launch_browser') ? undefined : json['auto_launch_browser'],
        'showWarnings': !exists(json, 'show_warnings') ? undefined : json['show_warnings'],
        'showGradioDeprecationWarnings': !exists(json, 'show_gradio_deprecation_warnings') ? undefined : json['show_gradio_deprecation_warnings'],
        'memmonPollRate': !exists(json, 'memmon_poll_rate') ? undefined : json['memmon_poll_rate'],
        'samplesLogStdout': !exists(json, 'samples_log_stdout') ? undefined : json['samples_log_stdout'],
        'multipleTqdm': !exists(json, 'multiple_tqdm') ? undefined : json['multiple_tqdm'],
        'printHypernetExtra': !exists(json, 'print_hypernet_extra') ? undefined : json['print_hypernet_extra'],
        'listHiddenFiles': !exists(json, 'list_hidden_files') ? undefined : json['list_hidden_files'],
        'disableMmapLoadSafetensors': !exists(json, 'disable_mmap_load_safetensors') ? undefined : json['disable_mmap_load_safetensors'],
        'hideLdmPrints': !exists(json, 'hide_ldm_prints') ? undefined : json['hide_ldm_prints'],
        'apiEnableRequests': !exists(json, 'api_enable_requests') ? undefined : json['api_enable_requests'],
        'apiForbidLocalRequests': !exists(json, 'api_forbid_local_requests') ? undefined : json['api_forbid_local_requests'],
        'apiUseragent': !exists(json, 'api_useragent') ? undefined : json['api_useragent'],
        'unloadModelsWhenTraining': !exists(json, 'unload_models_when_training') ? undefined : json['unload_models_when_training'],
        'pinMemory': !exists(json, 'pin_memory') ? undefined : json['pin_memory'],
        'saveOptimizerState': !exists(json, 'save_optimizer_state') ? undefined : json['save_optimizer_state'],
        'saveTrainingSettingsToTxt': !exists(json, 'save_training_settings_to_txt') ? undefined : json['save_training_settings_to_txt'],
        'datasetFilenameWordRegex': !exists(json, 'dataset_filename_word_regex') ? undefined : json['dataset_filename_word_regex'],
        'datasetFilenameJoinString': !exists(json, 'dataset_filename_join_string') ? undefined : json['dataset_filename_join_string'],
        'trainingImageRepeatsPerEpoch': !exists(json, 'training_image_repeats_per_epoch') ? undefined : json['training_image_repeats_per_epoch'],
        'trainingWriteCsvEvery': !exists(json, 'training_write_csv_every') ? undefined : json['training_write_csv_every'],
        'trainingXattentionOptimizations': !exists(json, 'training_xattention_optimizations') ? undefined : json['training_xattention_optimizations'],
        'trainingEnableTensorboard': !exists(json, 'training_enable_tensorboard') ? undefined : json['training_enable_tensorboard'],
        'trainingTensorboardSaveImages': !exists(json, 'training_tensorboard_save_images') ? undefined : json['training_tensorboard_save_images'],
        'trainingTensorboardFlushEvery': !exists(json, 'training_tensorboard_flush_every') ? undefined : json['training_tensorboard_flush_every'],
        'sdModelCheckpoint': !exists(json, 'sd_model_checkpoint') ? undefined : json['sd_model_checkpoint'],
        'sdCheckpointsLimit': !exists(json, 'sd_checkpoints_limit') ? undefined : json['sd_checkpoints_limit'],
        'sdCheckpointsKeepInCpu': !exists(json, 'sd_checkpoints_keep_in_cpu') ? undefined : json['sd_checkpoints_keep_in_cpu'],
        'sdCheckpointCache': !exists(json, 'sd_checkpoint_cache') ? undefined : json['sd_checkpoint_cache'],
        'sdUnet': !exists(json, 'sd_unet') ? undefined : json['sd_unet'],
        'enableQuantization': !exists(json, 'enable_quantization') ? undefined : json['enable_quantization'],
        'enableEmphasis': !exists(json, 'enable_emphasis') ? undefined : json['enable_emphasis'],
        'enableBatchSeeds': !exists(json, 'enable_batch_seeds') ? undefined : json['enable_batch_seeds'],
        'commaPaddingBacktrack': !exists(json, 'comma_padding_backtrack') ? undefined : json['comma_padding_backtrack'],
        'cLIPStopAtLastLayers': !exists(json, 'CLIP_stop_at_last_layers') ? undefined : json['CLIP_stop_at_last_layers'],
        'upcastAttn': !exists(json, 'upcast_attn') ? undefined : json['upcast_attn'],
        'randnSource': !exists(json, 'randn_source') ? undefined : json['randn_source'],
        'tiling': !exists(json, 'tiling') ? undefined : json['tiling'],
        'hiresFixRefinerPass': !exists(json, 'hires_fix_refiner_pass') ? undefined : json['hires_fix_refiner_pass'],
        'sdxlCropTop': !exists(json, 'sdxl_crop_top') ? undefined : json['sdxl_crop_top'],
        'sdxlCropLeft': !exists(json, 'sdxl_crop_left') ? undefined : json['sdxl_crop_left'],
        'sdxlRefinerLowAestheticScore': !exists(json, 'sdxl_refiner_low_aesthetic_score') ? undefined : json['sdxl_refiner_low_aesthetic_score'],
        'sdxlRefinerHighAestheticScore': !exists(json, 'sdxl_refiner_high_aesthetic_score') ? undefined : json['sdxl_refiner_high_aesthetic_score'],
        'sdVaeExplanation': !exists(json, 'sd_vae_explanation') ? undefined : json['sd_vae_explanation'],
        'sdVaeCheckpointCache': !exists(json, 'sd_vae_checkpoint_cache') ? undefined : json['sd_vae_checkpoint_cache'],
        'sdVae': !exists(json, 'sd_vae') ? undefined : json['sd_vae'],
        'sdVaeOverridesPerModelPreferences': !exists(json, 'sd_vae_overrides_per_model_preferences') ? undefined : json['sd_vae_overrides_per_model_preferences'],
        'autoVaePrecision': !exists(json, 'auto_vae_precision') ? undefined : json['auto_vae_precision'],
        'sdVaeEncodeMethod': !exists(json, 'sd_vae_encode_method') ? undefined : json['sd_vae_encode_method'],
        'sdVaeDecodeMethod': !exists(json, 'sd_vae_decode_method') ? undefined : json['sd_vae_decode_method'],
        'inpaintingMaskWeight': !exists(json, 'inpainting_mask_weight') ? undefined : json['inpainting_mask_weight'],
        'initialNoiseMultiplier': !exists(json, 'initial_noise_multiplier') ? undefined : json['initial_noise_multiplier'],
        'img2imgExtraNoise': !exists(json, 'img2img_extra_noise') ? undefined : json['img2img_extra_noise'],
        'img2imgColorCorrection': !exists(json, 'img2img_color_correction') ? undefined : json['img2img_color_correction'],
        'img2imgFixSteps': !exists(json, 'img2img_fix_steps') ? undefined : json['img2img_fix_steps'],
        'img2imgBackgroundColor': !exists(json, 'img2img_background_color') ? undefined : json['img2img_background_color'],
        'img2imgEditorHeight': !exists(json, 'img2img_editor_height') ? undefined : json['img2img_editor_height'],
        'img2imgSketchDefaultBrushColor': !exists(json, 'img2img_sketch_default_brush_color') ? undefined : json['img2img_sketch_default_brush_color'],
        'img2imgInpaintMaskBrushColor': !exists(json, 'img2img_inpaint_mask_brush_color') ? undefined : json['img2img_inpaint_mask_brush_color'],
        'img2imgInpaintSketchDefaultBrushColor': !exists(json, 'img2img_inpaint_sketch_default_brush_color') ? undefined : json['img2img_inpaint_sketch_default_brush_color'],
        'returnMask': !exists(json, 'return_mask') ? undefined : json['return_mask'],
        'returnMaskComposite': !exists(json, 'return_mask_composite') ? undefined : json['return_mask_composite'],
        'crossAttentionOptimization': !exists(json, 'cross_attention_optimization') ? undefined : json['cross_attention_optimization'],
        'sMinUncond': !exists(json, 's_min_uncond') ? undefined : json['s_min_uncond'],
        'tokenMergingRatio': !exists(json, 'token_merging_ratio') ? undefined : json['token_merging_ratio'],
        'tokenMergingRatioImg2img': !exists(json, 'token_merging_ratio_img2img') ? undefined : json['token_merging_ratio_img2img'],
        'tokenMergingRatioHr': !exists(json, 'token_merging_ratio_hr') ? undefined : json['token_merging_ratio_hr'],
        'padCondUncond': !exists(json, 'pad_cond_uncond') ? undefined : json['pad_cond_uncond'],
        'persistentCondCache': !exists(json, 'persistent_cond_cache') ? undefined : json['persistent_cond_cache'],
        'batchCondUncond': !exists(json, 'batch_cond_uncond') ? undefined : json['batch_cond_uncond'],
        'useOldEmphasisImplementation': !exists(json, 'use_old_emphasis_implementation') ? undefined : json['use_old_emphasis_implementation'],
        'useOldKarrasSchedulerSigmas': !exists(json, 'use_old_karras_scheduler_sigmas') ? undefined : json['use_old_karras_scheduler_sigmas'],
        'noDpmppSdeBatchDeterminism': !exists(json, 'no_dpmpp_sde_batch_determinism') ? undefined : json['no_dpmpp_sde_batch_determinism'],
        'useOldHiresFixWidthHeight': !exists(json, 'use_old_hires_fix_width_height') ? undefined : json['use_old_hires_fix_width_height'],
        'dontFixSecondOrderSamplersSchedule': !exists(json, 'dont_fix_second_order_samplers_schedule') ? undefined : json['dont_fix_second_order_samplers_schedule'],
        'hiresFixUseFirstpassConds': !exists(json, 'hires_fix_use_firstpass_conds') ? undefined : json['hires_fix_use_firstpass_conds'],
        'useOldScheduling': !exists(json, 'use_old_scheduling') ? undefined : json['use_old_scheduling'],
        'interrogateKeepModelsInMemory': !exists(json, 'interrogate_keep_models_in_memory') ? undefined : json['interrogate_keep_models_in_memory'],
        'interrogateReturnRanks': !exists(json, 'interrogate_return_ranks') ? undefined : json['interrogate_return_ranks'],
        'interrogateClipNumBeams': !exists(json, 'interrogate_clip_num_beams') ? undefined : json['interrogate_clip_num_beams'],
        'interrogateClipMinLength': !exists(json, 'interrogate_clip_min_length') ? undefined : json['interrogate_clip_min_length'],
        'interrogateClipMaxLength': !exists(json, 'interrogate_clip_max_length') ? undefined : json['interrogate_clip_max_length'],
        'interrogateClipDictLimit': !exists(json, 'interrogate_clip_dict_limit') ? undefined : json['interrogate_clip_dict_limit'],
        'interrogateClipSkipCategories': !exists(json, 'interrogate_clip_skip_categories') ? undefined : json['interrogate_clip_skip_categories'],
        'interrogateDeepbooruScoreThreshold': !exists(json, 'interrogate_deepbooru_score_threshold') ? undefined : json['interrogate_deepbooru_score_threshold'],
        'deepbooruSortAlpha': !exists(json, 'deepbooru_sort_alpha') ? undefined : json['deepbooru_sort_alpha'],
        'deepbooruUseSpaces': !exists(json, 'deepbooru_use_spaces') ? undefined : json['deepbooru_use_spaces'],
        'deepbooruEscape': !exists(json, 'deepbooru_escape') ? undefined : json['deepbooru_escape'],
        'deepbooruFilterTags': !exists(json, 'deepbooru_filter_tags') ? undefined : json['deepbooru_filter_tags'],
        'extraNetworksShowHiddenDirectories': !exists(json, 'extra_networks_show_hidden_directories') ? undefined : json['extra_networks_show_hidden_directories'],
        'extraNetworksHiddenModels': !exists(json, 'extra_networks_hidden_models') ? undefined : json['extra_networks_hidden_models'],
        'extraNetworksDefaultMultiplier': !exists(json, 'extra_networks_default_multiplier') ? undefined : json['extra_networks_default_multiplier'],
        'extraNetworksCardWidth': !exists(json, 'extra_networks_card_width') ? undefined : json['extra_networks_card_width'],
        'extraNetworksCardHeight': !exists(json, 'extra_networks_card_height') ? undefined : json['extra_networks_card_height'],
        'extraNetworksCardTextScale': !exists(json, 'extra_networks_card_text_scale') ? undefined : json['extra_networks_card_text_scale'],
        'extraNetworksCardShowDesc': !exists(json, 'extra_networks_card_show_desc') ? undefined : json['extra_networks_card_show_desc'],
        'extraNetworksAddTextSeparator': !exists(json, 'extra_networks_add_text_separator') ? undefined : json['extra_networks_add_text_separator'],
        'uiExtraNetworksTabReorder': !exists(json, 'ui_extra_networks_tab_reorder') ? undefined : json['ui_extra_networks_tab_reorder'],
        'textualInversionPrintAtLoad': !exists(json, 'textual_inversion_print_at_load') ? undefined : json['textual_inversion_print_at_load'],
        'textualInversionAddHashesToInfotext': !exists(json, 'textual_inversion_add_hashes_to_infotext') ? undefined : json['textual_inversion_add_hashes_to_infotext'],
        'sdHypernetwork': !exists(json, 'sd_hypernetwork') ? undefined : json['sd_hypernetwork'],
        'localization': !exists(json, 'localization') ? undefined : json['localization'],
        'gradioTheme': !exists(json, 'gradio_theme') ? undefined : json['gradio_theme'],
        'gradioThemesCache': !exists(json, 'gradio_themes_cache') ? undefined : json['gradio_themes_cache'],
        'galleryHeight': !exists(json, 'gallery_height') ? undefined : json['gallery_height'],
        'returnGrid': !exists(json, 'return_grid') ? undefined : json['return_grid'],
        'doNotShowImages': !exists(json, 'do_not_show_images') ? undefined : json['do_not_show_images'],
        'sendSeed': !exists(json, 'send_seed') ? undefined : json['send_seed'],
        'sendSize': !exists(json, 'send_size') ? undefined : json['send_size'],
        'jsModalLightbox': !exists(json, 'js_modal_lightbox') ? undefined : json['js_modal_lightbox'],
        'jsModalLightboxInitiallyZoomed': !exists(json, 'js_modal_lightbox_initially_zoomed') ? undefined : json['js_modal_lightbox_initially_zoomed'],
        'jsModalLightboxGamepad': !exists(json, 'js_modal_lightbox_gamepad') ? undefined : json['js_modal_lightbox_gamepad'],
        'jsModalLightboxGamepadRepeat': !exists(json, 'js_modal_lightbox_gamepad_repeat') ? undefined : json['js_modal_lightbox_gamepad_repeat'],
        'showProgressInTitle': !exists(json, 'show_progress_in_title') ? undefined : json['show_progress_in_title'],
        'samplersInDropdown': !exists(json, 'samplers_in_dropdown') ? undefined : json['samplers_in_dropdown'],
        'dimensionsAndBatchTogether': !exists(json, 'dimensions_and_batch_together') ? undefined : json['dimensions_and_batch_together'],
        'keyeditPrecisionAttention': !exists(json, 'keyedit_precision_attention') ? undefined : json['keyedit_precision_attention'],
        'keyeditPrecisionExtra': !exists(json, 'keyedit_precision_extra') ? undefined : json['keyedit_precision_extra'],
        'keyeditDelimiters': !exists(json, 'keyedit_delimiters') ? undefined : json['keyedit_delimiters'],
        'keyeditMove': !exists(json, 'keyedit_move') ? undefined : json['keyedit_move'],
        'quicksettingsList': !exists(json, 'quicksettings_list') ? undefined : json['quicksettings_list'],
        'uiTabOrder': !exists(json, 'ui_tab_order') ? undefined : json['ui_tab_order'],
        'hiddenTabs': !exists(json, 'hidden_tabs') ? undefined : json['hidden_tabs'],
        'uiReorderList': !exists(json, 'ui_reorder_list') ? undefined : json['ui_reorder_list'],
        'hiresFixShowSampler': !exists(json, 'hires_fix_show_sampler') ? undefined : json['hires_fix_show_sampler'],
        'hiresFixShowPrompts': !exists(json, 'hires_fix_show_prompts') ? undefined : json['hires_fix_show_prompts'],
        'disableTokenCounters': !exists(json, 'disable_token_counters') ? undefined : json['disable_token_counters'],
        'addModelHashToInfo': !exists(json, 'add_model_hash_to_info') ? undefined : json['add_model_hash_to_info'],
        'addModelNameToInfo': !exists(json, 'add_model_name_to_info') ? undefined : json['add_model_name_to_info'],
        'addUserNameToInfo': !exists(json, 'add_user_name_to_info') ? undefined : json['add_user_name_to_info'],
        'addVersionToInfotext': !exists(json, 'add_version_to_infotext') ? undefined : json['add_version_to_infotext'],
        'disableWeightsAutoSwap': !exists(json, 'disable_weights_auto_swap') ? undefined : json['disable_weights_auto_swap'],
        'infotextStyles': !exists(json, 'infotext_styles') ? undefined : json['infotext_styles'],
        'showProgressbar': !exists(json, 'show_progressbar') ? undefined : json['show_progressbar'],
        'livePreviewsEnable': !exists(json, 'live_previews_enable') ? undefined : json['live_previews_enable'],
        'livePreviewsImageFormat': !exists(json, 'live_previews_image_format') ? undefined : json['live_previews_image_format'],
        'showProgressGrid': !exists(json, 'show_progress_grid') ? undefined : json['show_progress_grid'],
        'showProgressEveryNSteps': !exists(json, 'show_progress_every_n_steps') ? undefined : json['show_progress_every_n_steps'],
        'showProgressType': !exists(json, 'show_progress_type') ? undefined : json['show_progress_type'],
        'livePreviewAllowLowvramFull': !exists(json, 'live_preview_allow_lowvram_full') ? undefined : json['live_preview_allow_lowvram_full'],
        'livePreviewContent': !exists(json, 'live_preview_content') ? undefined : json['live_preview_content'],
        'livePreviewRefreshPeriod': !exists(json, 'live_preview_refresh_period') ? undefined : json['live_preview_refresh_period'],
        'livePreviewFastInterrupt': !exists(json, 'live_preview_fast_interrupt') ? undefined : json['live_preview_fast_interrupt'],
        'hideSamplers': !exists(json, 'hide_samplers') ? undefined : json['hide_samplers'],
        'etaDdim': !exists(json, 'eta_ddim') ? undefined : json['eta_ddim'],
        'etaAncestral': !exists(json, 'eta_ancestral') ? undefined : json['eta_ancestral'],
        'ddimDiscretize': !exists(json, 'ddim_discretize') ? undefined : json['ddim_discretize'],
        'sChurn': !exists(json, 's_churn') ? undefined : json['s_churn'],
        'sTmin': !exists(json, 's_tmin') ? undefined : json['s_tmin'],
        'sTmax': !exists(json, 's_tmax') ? undefined : json['s_tmax'],
        'sNoise': !exists(json, 's_noise') ? undefined : json['s_noise'],
        'kSchedType': !exists(json, 'k_sched_type') ? undefined : json['k_sched_type'],
        'sigmaMin': !exists(json, 'sigma_min') ? undefined : json['sigma_min'],
        'sigmaMax': !exists(json, 'sigma_max') ? undefined : json['sigma_max'],
        'rho': !exists(json, 'rho') ? undefined : json['rho'],
        'etaNoiseSeedDelta': !exists(json, 'eta_noise_seed_delta') ? undefined : json['eta_noise_seed_delta'],
        'alwaysDiscardNextToLastSigma': !exists(json, 'always_discard_next_to_last_sigma') ? undefined : json['always_discard_next_to_last_sigma'],
        'sgmNoiseMultiplier': !exists(json, 'sgm_noise_multiplier') ? undefined : json['sgm_noise_multiplier'],
        'uniPcVariant': !exists(json, 'uni_pc_variant') ? undefined : json['uni_pc_variant'],
        'uniPcSkipType': !exists(json, 'uni_pc_skip_type') ? undefined : json['uni_pc_skip_type'],
        'uniPcOrder': !exists(json, 'uni_pc_order') ? undefined : json['uni_pc_order'],
        'uniPcLowerOrderFinal': !exists(json, 'uni_pc_lower_order_final') ? undefined : json['uni_pc_lower_order_final'],
        'postprocessingEnableInMainUi': !exists(json, 'postprocessing_enable_in_main_ui') ? undefined : json['postprocessing_enable_in_main_ui'],
        'postprocessingOperationOrder': !exists(json, 'postprocessing_operation_order') ? undefined : json['postprocessing_operation_order'],
        'upscalingMaxImagesInCache': !exists(json, 'upscaling_max_images_in_cache') ? undefined : json['upscaling_max_images_in_cache'],
        'disabledExtensions': !exists(json, 'disabled_extensions') ? undefined : json['disabled_extensions'],
        'disableAllExtensions': !exists(json, 'disable_all_extensions') ? undefined : json['disable_all_extensions'],
        'restoreConfigStateFile': !exists(json, 'restore_config_state_file') ? undefined : json['restore_config_state_file'],
        'sdCheckpointHash': !exists(json, 'sd_checkpoint_hash') ? undefined : json['sd_checkpoint_hash'],
    };
}

export function OptionsToJSON(value?: Options | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'samples_save': value.samplesSave,
        'samples_format': value.samplesFormat,
        'samples_filename_pattern': value.samplesFilenamePattern,
        'save_images_add_number': value.saveImagesAddNumber,
        'grid_save': value.gridSave,
        'grid_format': value.gridFormat,
        'grid_extended_filename': value.gridExtendedFilename,
        'grid_only_if_multiple': value.gridOnlyIfMultiple,
        'grid_prevent_empty_spots': value.gridPreventEmptySpots,
        'grid_zip_filename_pattern': value.gridZipFilenamePattern,
        'n_rows': value.nRows,
        'font': value.font,
        'grid_text_active_color': value.gridTextActiveColor,
        'grid_text_inactive_color': value.gridTextInactiveColor,
        'grid_background_color': value.gridBackgroundColor,
        'enable_pnginfo': value.enablePnginfo,
        'save_txt': value.saveTxt,
        'save_images_before_face_restoration': value.saveImagesBeforeFaceRestoration,
        'save_images_before_highres_fix': value.saveImagesBeforeHighresFix,
        'save_images_before_color_correction': value.saveImagesBeforeColorCorrection,
        'save_mask': value.saveMask,
        'save_mask_composite': value.saveMaskComposite,
        'jpeg_quality': value.jpegQuality,
        'webp_lossless': value.webpLossless,
        'export_for_4chan': value.exportFor4chan,
        'img_downscale_threshold': value.imgDownscaleThreshold,
        'target_side_length': value.targetSideLength,
        'img_max_size_mp': value.imgMaxSizeMp,
        'use_original_name_batch': value.useOriginalNameBatch,
        'use_upscaler_name_as_suffix': value.useUpscalerNameAsSuffix,
        'save_selected_only': value.saveSelectedOnly,
        'save_init_img': value.saveInitImg,
        'temp_dir': value.tempDir,
        'clean_temp_dir_at_start': value.cleanTempDirAtStart,
        'save_incomplete_images': value.saveIncompleteImages,
        'outdir_samples': value.outdirSamples,
        'outdir_txt2img_samples': value.outdirTxt2imgSamples,
        'outdir_img2img_samples': value.outdirImg2imgSamples,
        'outdir_extras_samples': value.outdirExtrasSamples,
        'outdir_grids': value.outdirGrids,
        'outdir_txt2img_grids': value.outdirTxt2imgGrids,
        'outdir_img2img_grids': value.outdirImg2imgGrids,
        'outdir_save': value.outdirSave,
        'outdir_init_images': value.outdirInitImages,
        'save_to_dirs': value.saveToDirs,
        'grid_save_to_dirs': value.gridSaveToDirs,
        'use_save_to_dirs_for_ui': value.useSaveToDirsForUi,
        'directories_filename_pattern': value.directoriesFilenamePattern,
        'directories_max_prompt_words': value.directoriesMaxPromptWords,
        'ESRGAN_tile': value.eSRGANTile,
        'ESRGAN_tile_overlap': value.eSRGANTileOverlap,
        'realesrgan_enabled_models': value.realesrganEnabledModels,
        'upscaler_for_img2img': value.upscalerForImg2img,
        'face_restoration': value.faceRestoration,
        'face_restoration_model': value.faceRestorationModel,
        'code_former_weight': value.codeFormerWeight,
        'face_restoration_unload': value.faceRestorationUnload,
        'auto_launch_browser': value.autoLaunchBrowser,
        'show_warnings': value.showWarnings,
        'show_gradio_deprecation_warnings': value.showGradioDeprecationWarnings,
        'memmon_poll_rate': value.memmonPollRate,
        'samples_log_stdout': value.samplesLogStdout,
        'multiple_tqdm': value.multipleTqdm,
        'print_hypernet_extra': value.printHypernetExtra,
        'list_hidden_files': value.listHiddenFiles,
        'disable_mmap_load_safetensors': value.disableMmapLoadSafetensors,
        'hide_ldm_prints': value.hideLdmPrints,
        'api_enable_requests': value.apiEnableRequests,
        'api_forbid_local_requests': value.apiForbidLocalRequests,
        'api_useragent': value.apiUseragent,
        'unload_models_when_training': value.unloadModelsWhenTraining,
        'pin_memory': value.pinMemory,
        'save_optimizer_state': value.saveOptimizerState,
        'save_training_settings_to_txt': value.saveTrainingSettingsToTxt,
        'dataset_filename_word_regex': value.datasetFilenameWordRegex,
        'dataset_filename_join_string': value.datasetFilenameJoinString,
        'training_image_repeats_per_epoch': value.trainingImageRepeatsPerEpoch,
        'training_write_csv_every': value.trainingWriteCsvEvery,
        'training_xattention_optimizations': value.trainingXattentionOptimizations,
        'training_enable_tensorboard': value.trainingEnableTensorboard,
        'training_tensorboard_save_images': value.trainingTensorboardSaveImages,
        'training_tensorboard_flush_every': value.trainingTensorboardFlushEvery,
        'sd_model_checkpoint': value.sdModelCheckpoint,
        'sd_checkpoints_limit': value.sdCheckpointsLimit,
        'sd_checkpoints_keep_in_cpu': value.sdCheckpointsKeepInCpu,
        'sd_checkpoint_cache': value.sdCheckpointCache,
        'sd_unet': value.sdUnet,
        'enable_quantization': value.enableQuantization,
        'enable_emphasis': value.enableEmphasis,
        'enable_batch_seeds': value.enableBatchSeeds,
        'comma_padding_backtrack': value.commaPaddingBacktrack,
        'CLIP_stop_at_last_layers': value.cLIPStopAtLastLayers,
        'upcast_attn': value.upcastAttn,
        'randn_source': value.randnSource,
        'tiling': value.tiling,
        'hires_fix_refiner_pass': value.hiresFixRefinerPass,
        'sdxl_crop_top': value.sdxlCropTop,
        'sdxl_crop_left': value.sdxlCropLeft,
        'sdxl_refiner_low_aesthetic_score': value.sdxlRefinerLowAestheticScore,
        'sdxl_refiner_high_aesthetic_score': value.sdxlRefinerHighAestheticScore,
        'sd_vae_explanation': value.sdVaeExplanation,
        'sd_vae_checkpoint_cache': value.sdVaeCheckpointCache,
        'sd_vae': value.sdVae,
        'sd_vae_overrides_per_model_preferences': value.sdVaeOverridesPerModelPreferences,
        'auto_vae_precision': value.autoVaePrecision,
        'sd_vae_encode_method': value.sdVaeEncodeMethod,
        'sd_vae_decode_method': value.sdVaeDecodeMethod,
        'inpainting_mask_weight': value.inpaintingMaskWeight,
        'initial_noise_multiplier': value.initialNoiseMultiplier,
        'img2img_extra_noise': value.img2imgExtraNoise,
        'img2img_color_correction': value.img2imgColorCorrection,
        'img2img_fix_steps': value.img2imgFixSteps,
        'img2img_background_color': value.img2imgBackgroundColor,
        'img2img_editor_height': value.img2imgEditorHeight,
        'img2img_sketch_default_brush_color': value.img2imgSketchDefaultBrushColor,
        'img2img_inpaint_mask_brush_color': value.img2imgInpaintMaskBrushColor,
        'img2img_inpaint_sketch_default_brush_color': value.img2imgInpaintSketchDefaultBrushColor,
        'return_mask': value.returnMask,
        'return_mask_composite': value.returnMaskComposite,
        'cross_attention_optimization': value.crossAttentionOptimization,
        's_min_uncond': value.sMinUncond,
        'token_merging_ratio': value.tokenMergingRatio,
        'token_merging_ratio_img2img': value.tokenMergingRatioImg2img,
        'token_merging_ratio_hr': value.tokenMergingRatioHr,
        'pad_cond_uncond': value.padCondUncond,
        'persistent_cond_cache': value.persistentCondCache,
        'batch_cond_uncond': value.batchCondUncond,
        'use_old_emphasis_implementation': value.useOldEmphasisImplementation,
        'use_old_karras_scheduler_sigmas': value.useOldKarrasSchedulerSigmas,
        'no_dpmpp_sde_batch_determinism': value.noDpmppSdeBatchDeterminism,
        'use_old_hires_fix_width_height': value.useOldHiresFixWidthHeight,
        'dont_fix_second_order_samplers_schedule': value.dontFixSecondOrderSamplersSchedule,
        'hires_fix_use_firstpass_conds': value.hiresFixUseFirstpassConds,
        'use_old_scheduling': value.useOldScheduling,
        'interrogate_keep_models_in_memory': value.interrogateKeepModelsInMemory,
        'interrogate_return_ranks': value.interrogateReturnRanks,
        'interrogate_clip_num_beams': value.interrogateClipNumBeams,
        'interrogate_clip_min_length': value.interrogateClipMinLength,
        'interrogate_clip_max_length': value.interrogateClipMaxLength,
        'interrogate_clip_dict_limit': value.interrogateClipDictLimit,
        'interrogate_clip_skip_categories': value.interrogateClipSkipCategories,
        'interrogate_deepbooru_score_threshold': value.interrogateDeepbooruScoreThreshold,
        'deepbooru_sort_alpha': value.deepbooruSortAlpha,
        'deepbooru_use_spaces': value.deepbooruUseSpaces,
        'deepbooru_escape': value.deepbooruEscape,
        'deepbooru_filter_tags': value.deepbooruFilterTags,
        'extra_networks_show_hidden_directories': value.extraNetworksShowHiddenDirectories,
        'extra_networks_hidden_models': value.extraNetworksHiddenModels,
        'extra_networks_default_multiplier': value.extraNetworksDefaultMultiplier,
        'extra_networks_card_width': value.extraNetworksCardWidth,
        'extra_networks_card_height': value.extraNetworksCardHeight,
        'extra_networks_card_text_scale': value.extraNetworksCardTextScale,
        'extra_networks_card_show_desc': value.extraNetworksCardShowDesc,
        'extra_networks_add_text_separator': value.extraNetworksAddTextSeparator,
        'ui_extra_networks_tab_reorder': value.uiExtraNetworksTabReorder,
        'textual_inversion_print_at_load': value.textualInversionPrintAtLoad,
        'textual_inversion_add_hashes_to_infotext': value.textualInversionAddHashesToInfotext,
        'sd_hypernetwork': value.sdHypernetwork,
        'localization': value.localization,
        'gradio_theme': value.gradioTheme,
        'gradio_themes_cache': value.gradioThemesCache,
        'gallery_height': value.galleryHeight,
        'return_grid': value.returnGrid,
        'do_not_show_images': value.doNotShowImages,
        'send_seed': value.sendSeed,
        'send_size': value.sendSize,
        'js_modal_lightbox': value.jsModalLightbox,
        'js_modal_lightbox_initially_zoomed': value.jsModalLightboxInitiallyZoomed,
        'js_modal_lightbox_gamepad': value.jsModalLightboxGamepad,
        'js_modal_lightbox_gamepad_repeat': value.jsModalLightboxGamepadRepeat,
        'show_progress_in_title': value.showProgressInTitle,
        'samplers_in_dropdown': value.samplersInDropdown,
        'dimensions_and_batch_together': value.dimensionsAndBatchTogether,
        'keyedit_precision_attention': value.keyeditPrecisionAttention,
        'keyedit_precision_extra': value.keyeditPrecisionExtra,
        'keyedit_delimiters': value.keyeditDelimiters,
        'keyedit_move': value.keyeditMove,
        'quicksettings_list': value.quicksettingsList,
        'ui_tab_order': value.uiTabOrder,
        'hidden_tabs': value.hiddenTabs,
        'ui_reorder_list': value.uiReorderList,
        'hires_fix_show_sampler': value.hiresFixShowSampler,
        'hires_fix_show_prompts': value.hiresFixShowPrompts,
        'disable_token_counters': value.disableTokenCounters,
        'add_model_hash_to_info': value.addModelHashToInfo,
        'add_model_name_to_info': value.addModelNameToInfo,
        'add_user_name_to_info': value.addUserNameToInfo,
        'add_version_to_infotext': value.addVersionToInfotext,
        'disable_weights_auto_swap': value.disableWeightsAutoSwap,
        'infotext_styles': value.infotextStyles,
        'show_progressbar': value.showProgressbar,
        'live_previews_enable': value.livePreviewsEnable,
        'live_previews_image_format': value.livePreviewsImageFormat,
        'show_progress_grid': value.showProgressGrid,
        'show_progress_every_n_steps': value.showProgressEveryNSteps,
        'show_progress_type': value.showProgressType,
        'live_preview_allow_lowvram_full': value.livePreviewAllowLowvramFull,
        'live_preview_content': value.livePreviewContent,
        'live_preview_refresh_period': value.livePreviewRefreshPeriod,
        'live_preview_fast_interrupt': value.livePreviewFastInterrupt,
        'hide_samplers': value.hideSamplers,
        'eta_ddim': value.etaDdim,
        'eta_ancestral': value.etaAncestral,
        'ddim_discretize': value.ddimDiscretize,
        's_churn': value.sChurn,
        's_tmin': value.sTmin,
        's_tmax': value.sTmax,
        's_noise': value.sNoise,
        'k_sched_type': value.kSchedType,
        'sigma_min': value.sigmaMin,
        'sigma_max': value.sigmaMax,
        'rho': value.rho,
        'eta_noise_seed_delta': value.etaNoiseSeedDelta,
        'always_discard_next_to_last_sigma': value.alwaysDiscardNextToLastSigma,
        'sgm_noise_multiplier': value.sgmNoiseMultiplier,
        'uni_pc_variant': value.uniPcVariant,
        'uni_pc_skip_type': value.uniPcSkipType,
        'uni_pc_order': value.uniPcOrder,
        'uni_pc_lower_order_final': value.uniPcLowerOrderFinal,
        'postprocessing_enable_in_main_ui': value.postprocessingEnableInMainUi,
        'postprocessing_operation_order': value.postprocessingOperationOrder,
        'upscaling_max_images_in_cache': value.upscalingMaxImagesInCache,
        'disabled_extensions': value.disabledExtensions,
        'disable_all_extensions': value.disableAllExtensions,
        'restore_config_state_file': value.restoreConfigStateFile,
        'sd_checkpoint_hash': value.sdCheckpointHash,
    };
}

