/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PNGInfoResponse
 */
export interface PNGInfoResponse {
    /**
     * A string with the parameters used to generate the image
     * @type {string}
     * @memberof PNGInfoResponse
     */
    info: string;
    /**
     * An object containing all the info the image had
     * @type {object}
     * @memberof PNGInfoResponse
     */
    items: object;
}

/**
 * Check if a given object implements the PNGInfoResponse interface.
 */
export function instanceOfPNGInfoResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "info" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function PNGInfoResponseFromJSON(json: any): PNGInfoResponse {
    return PNGInfoResponseFromJSONTyped(json, false);
}

export function PNGInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PNGInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': json['info'],
        'items': json['items'],
    };
}

export function PNGInfoResponseToJSON(value?: PNGInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': value.info,
        'items': value.items,
    };
}

