/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProgressRequest
 */
export interface ProgressRequest {
    /**
     * id of the task to get progress for
     * @type {string}
     * @memberof ProgressRequest
     */
    idTask?: string;
    /**
     * id of last received last preview image
     * @type {number}
     * @memberof ProgressRequest
     */
    idLivePreview?: number;
    /**
     * boolean flag indicating whether to include the live preview image
     * @type {boolean}
     * @memberof ProgressRequest
     */
    livePreview?: boolean;
}

/**
 * Check if a given object implements the ProgressRequest interface.
 */
export function instanceOfProgressRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProgressRequestFromJSON(json: any): ProgressRequest {
    return ProgressRequestFromJSONTyped(json, false);
}

export function ProgressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgressRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idTask': !exists(json, 'id_task') ? undefined : json['id_task'],
        'idLivePreview': !exists(json, 'id_live_preview') ? undefined : json['id_live_preview'],
        'livePreview': !exists(json, 'live_preview') ? undefined : json['live_preview'],
    };
}

export function ProgressRequestToJSON(value?: ProgressRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id_task': value.idTask,
        'id_live_preview': value.idLivePreview,
        'live_preview': value.livePreview,
    };
}

