/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetBody
 */
export interface ResetBody {
    /**
     * 
     * @type {string}
     * @memberof ResetBody
     */
    sessionHash: string;
    /**
     * 
     * @type {number}
     * @memberof ResetBody
     */
    fnIndex: number;
}

/**
 * Check if a given object implements the ResetBody interface.
 */
export function instanceOfResetBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sessionHash" in value;
    isInstance = isInstance && "fnIndex" in value;

    return isInstance;
}

export function ResetBodyFromJSON(json: any): ResetBody {
    return ResetBodyFromJSONTyped(json, false);
}

export function ResetBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionHash': json['session_hash'],
        'fnIndex': json['fn_index'],
    };
}

export function ResetBodyToJSON(value?: ResetBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'session_hash': value.sessionHash,
        'fn_index': value.fnIndex,
    };
}

