/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScriptsList
 */
export interface ScriptsList {
    /**
     * Titles of scripts (txt2img)
     * @type {Array<any>}
     * @memberof ScriptsList
     */
    txt2img?: Array<any>;
    /**
     * Titles of scripts (img2img)
     * @type {Array<any>}
     * @memberof ScriptsList
     */
    img2img?: Array<any>;
}

/**
 * Check if a given object implements the ScriptsList interface.
 */
export function instanceOfScriptsList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScriptsListFromJSON(json: any): ScriptsList {
    return ScriptsListFromJSONTyped(json, false);
}

export function ScriptsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScriptsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'txt2img': !exists(json, 'txt2img') ? undefined : json['txt2img'],
        'img2img': !exists(json, 'img2img') ? undefined : json['img2img'],
    };
}

export function ScriptsListToJSON(value?: ScriptsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'txt2img': value.txt2img,
        'img2img': value.img2img,
    };
}

