/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SDVaeItem
 */
export interface SDVaeItem {
    /**
     * 
     * @type {string}
     * @memberof SDVaeItem
     */
    modelName: string;
    /**
     * 
     * @type {string}
     * @memberof SDVaeItem
     */
    filename: string;
}

/**
 * Check if a given object implements the SDVaeItem interface.
 */
export function instanceOfSDVaeItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "modelName" in value;
    isInstance = isInstance && "filename" in value;

    return isInstance;
}

export function SDVaeItemFromJSON(json: any): SDVaeItem {
    return SDVaeItemFromJSONTyped(json, false);
}

export function SDVaeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SDVaeItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modelName': json['model_name'],
        'filename': json['filename'],
    };
}

export function SDVaeItemToJSON(value?: SDVaeItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model_name': value.modelName,
        'filename': value.filename,
    };
}

